before_script:
    - tar xf /tmp/nm_cache.tar && npm prune && npm install --silent && tar cf /tmp/nm_cache.tar node_modules

stages:
    - build
    - test

build:
    stage: build
    script:
        - ./node_modules/webpack/bin/webpack.js --colors --bail

eslint:
    stage: test
    script:
        - npm run-script lint
