before_script:
    - ./cached_npm.sh

stages:
    - build
    - test

build:
    stage: build
    script:
        - ./node_modules/webpack/bin/webpack.js --colors --bail

eslint:
    stage: test
    script:
        - npm run-script lint

mocha:
    stage: test
    script:
        - npm test
