before_script:
    - npm install --silent || true

stages:
    - build
    - test

build:
    stage: build
    script:
        - ./node_modules/webpack/bin/webpack.js --progress --colors --bail

eslint:
    stage: test
    script:
        - npm run-script lint
